[CRO] Types:
binary-com/deriv-analytics pull request #32
Opened 2023-11-22 10:09 UTC by NikitK-deriv

add types for dbot quick strategy

2023-11-22 10:09 UTC, review-deriv reviewed
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

2023-11-23 07:35 UTC, amir-deriv requested changes

2023-11-23 07:35 UTC, amir-deriv commented on src/types.ts
> +    form_source?: 'tradershub_dashboard_form' | 'tradershub_first_entrance' | '7_step'
```suggestion
    form_source?: 'tradershub_dashboard_form' | 'tradershub_first_entrance' | 'repeat_tour'
```

`7_step` as a `form_source` was a mistake, and I changed it after discussing with Denis, please revert to `repeat_tour`

2023-11-23 07:35 UTC, amir-deriv commented
@NikitK-deriv please bump up the version, since we are adding new types we should bump the version up

2023-11-23 07:40 UTC, amir-deriv approved these changes

2023-11-23 07:41 UTC, ali-hosseini-deriv approved these changes

2023-11-23 07:41 UTC, merged